# Generated by Django 3.0.3 on 2020-02-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeatedPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('position', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_player_count', models.IntegerField(default=0)),
                ('current_player_count', models.IntegerField(default=0)),
                ('small_blind', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('big_blind', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_buy_in', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('max_buy_in', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('game_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.GameVariant')),
            ],
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_player', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_user', to='website.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Table')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDepositWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='seated_players',
            field=models.ManyToManyField(through='website.SeatedPlayer', to='website.User'),
        ),
        migrations.AddField(
            model_name='table',
            name='table_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.TableType'),
        ),
        migrations.AddField(
            model_name='seatedplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AddField(
            model_name='seatedplayer',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Table'),
        ),
    ]
